name: Create Release

on:
  push:
    tags:
      - '*' # Push events to matching *, i.e. 1.0, 20.15.10

jobs:
  release-note:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.VERSION }}
      is_prerelease: ${{ env.IS_PRERELEASE }}
      message: ${{ env.TAG_MESSAGE }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Get Release Notes
        run: |
          TAG_MESSAGE=$(git tag -l --format="%(contents:subject)" ${{ github.ref_name }})
          echo "Release message: "$TAG_MESSAGE
          echo "TAG_MESSAGE=$TAG_MESSAGE" >> $GITHUB_ENV

      - name: Get update version and check prerelease
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "New version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          # Check if version starts with "0"
          if [[ $VERSION == 0* ]]; then
            IS_PRERELEASE=true
          else
            IS_PRERELEASE=false
          fi
          echo "IS_PRERELEASE=$IS_PRERELEASE" >> $GITHUB_ENV

  commit:
    needs: release-note
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Update version for repository
        run: |
          VERSION=${{ needs.release-note.outputs.version }}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Dump version to $VERSION"
          sed -i 's/"version": ".*"/"version": "'$VERSION'"/' composer.json

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update version to v${{ env.VERSION }}'
          add: '.'
          author_name: GitHub Actions
          author_email: actions@github.com
          committer_name: GitHub Actions

  build:
    needs: [commit, release-note]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.release-note.outputs.version }}
          name: ${{ needs.release-note.outputs.version }}
          body: |
            ${{ needs.release-note.outputs.message }}
          draft: false
          prerelease: ${{ needs.release-note.outputs.is_prerelease }}
          omitDraftDuringUpdate: true
